# Generated by Django 4.0.5 on 2022-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
