# Generated by Django 4.0.5 on 2022-10-27 15:25

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mainImage',
            field=models.ImageField(blank=True, upload_to=projects.models.Project.main_image_upload),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=projects.models.ProjectImages.image_upload),
        ),
    ]
