# Generated by Django 4.0.5 on 2022-11-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_mainimage_alter_projectimages_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
