# Generated by Django 4.0.5 on 2022-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
