# Generated by Django 5.0.7 on 2024-07-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_tag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectMainColor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='picture',
            field=models.ImageField(default='default_contributor.png', upload_to=''),
        ),
    ]
