# Generated by Django 5.0.7 on 2024-07-17 14:49

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_projectmaincolor_alter_contributor_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='headImage',
            field=models.ImageField(blank=True, upload_to=projects.models.Project.head_image_upload),
        ),
    ]
